language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
  - "travis_retry pip install tox-travis"
script:
  - tox
after_script:
  - cat .tox/$TOX_ENV/log/*.log
